plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
}

// The demo implementation of HubApi starts from the same data the server seeds its database with.
val demoSeedDirectory = rootProject.layout.projectDirectory.dir("server/src/main/resources/seed")
val demoSeedOutput = layout.buildDirectory.dir("generated/demoSeed")

val generateDemoSeed by tasks.registering {
    inputs.dir(demoSeedDirectory)
    outputs.dir(demoSeedOutput)
    val seedDirectory = demoSeedDirectory.asFile
    val outputDirectory = demoSeedOutput.get().asFile
    doLast {
        fun escaped(text: String): String =
            text
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("$", "\\$")
                .replace("\n", "\\n")

        // Split into short lines, so that the generated file passes ktlint like everything else
        fun literal(name: String): String =
            seedDirectory
                .resolve("$name.json")
                .readText()
                .replace("\r", "")
                .chunked(50)
                .mapIndexed { index, chunk -> (if (index == 0) "    " else "        ") + "\"" + escaped(chunk) + "\"" }
                .joinToString(" +\n")
        val target = outputDirectory.resolve("io/github/mfabisiak/hubmi/web/mock/DemoSeedJson.kt")
        target.parentFile.mkdirs()
        val constants =
            listOf("innovations", "challenges", "materials").joinToString("\n\n") { name ->
                "internal const val ${name.uppercase()}_JSON =\n${literal(name)}"
            }
        target.writeText(
            "// Generated by :web-client:generateDemoSeed from server/src/main/resources/seed; do not edit.\n" +
                "package io.github.mfabisiak.hubmi.web.mock\n\n$constants\n",
        )
    }
}

// Kotlin/JS library consumed by the React app in /web (npm: "hubmi-client", TypeScript definitions generated).
kotlin {
    js {
        outputModuleName = "hubmi-client"
        browser()
        binaries.library()
        generateTypeScriptDefinitions()
        compilerOptions {
            target = "es2015"
            optIn.add("kotlin.js.ExperimentalJsExport")
        }
    }

    sourceSets {
        jsMain {
            kotlin.srcDir(generateDemoSeed.map { demoSeedOutput })
        }
        jsMain.dependencies {
            api(project(":core"))
            implementation(libs.arrow.core)
            implementation(libs.ktor.clientCore)
            implementation(libs.ktor.clientJs)
            implementation(libs.ktor.clientResources)
            implementation(libs.ktor.clientContentNegotiationCommon)
            implementation(libs.ktor.serializationKotlinxJsonCommon)
        }
    }
}
