package io.github.mfabisiak.hubmi.web.assistant

import io.github.mfabisiak.hubmi.api.AssistEvent
import io.github.mfabisiak.hubmi.api.AssistResponse
import io.github.mfabisiak.hubmi.api.FlowDto
import io.github.mfabisiak.hubmi.api.FlowStepDto
import io.github.mfabisiak.hubmi.api.SimilarInnovationDto
import io.github.mfabisiak.hubmi.api.SuggestionDto
import io.github.mfabisiak.hubmi.web.innovations.InnovationSummaryJs
import io.github.mfabisiak.hubmi.web.innovations.toJs

@JsExport
class SimilarInnovationJs(
    val innovation: InnovationSummaryJs,
    /** Closeness in `0..1`. */
    val score: Double,
)

@JsExport
class SuggestionJs(
    val title: String,
    val rationale: String,
    val nextStep: String,
    /** Ids of the entries of `similar` the suggestion draws on. */
    val basedOnInnovationIds: Array<String>,
)

@JsExport
class FlowStepJs(
    /** An entry of [FlowJs.actors]. */
    val from: String,
    /** An entry of [FlowJs.actors]. */
    val to: String,
    val label: String,
)

/** The idea as steps between actors: draw it as a diagram and offer the numbered steps as its text alternative. */
@JsExport
class FlowJs(
    val actors: Array<String>,
    val steps: Array<FlowStepJs>,
)

/** What is known without the model: sent first, at once. */
@JsExport
class SimilarPartJs(
    val similar: Array<SimilarInnovationJs>,
    /** `NoveltyHint` name: `ALREADY_EXISTS`, `PARTIAL` or `NEW`. */
    val noveltyHint: String,
)

/** The whole answer; what `AssistStreamJs.result` resolves to, so a caller that does not stream only needs that. */
@JsExport
class AssistResponseJs(
    /** `AssistMode` name. */
    val mode: String,
    /** `AiStatus` name: `OK`, `UNAVAILABLE`, `INVALID_OUTPUT` or `NOT_REQUESTED`; `similar` is there in every case. */
    val aiStatus: String,
    /** Always true: show everything under `suggestions` and `flow` as generated by AI. */
    val aiGenerated: Boolean,
    val similar: Array<SimilarInnovationJs>,
    val noveltyHint: String,
    val suggestions: Array<SuggestionJs>,
    val flow: FlowJs?,
)

/**
 * Callbacks for the parts of an answer as they arrive; pass an object literal with any of them. They run in order:
 * `onSimilar` once, then `onSuggestion` for each suggestion (or `onFlow` once). A callback that throws is logged and
 * does not stop the stream.
 */
@JsExport
external interface AssistListenerJs {
    val onSimilar: ((SimilarPartJs) -> Unit)?
        get() = definedExternally
    val onSuggestion: ((SuggestionJs) -> Unit)?
        get() = definedExternally
    val onFlow: ((FlowJs) -> Unit)?
        get() = definedExternally
}

internal fun AssistResponse.toJs(): AssistResponseJs =
    AssistResponseJs(
        mode = mode.name,
        aiStatus = aiStatus.name,
        aiGenerated = aiGenerated,
        similar = similar.map { it.toJs() }.toTypedArray(),
        noveltyHint = noveltyHint.name,
        suggestions = suggestions.map { it.toJs() }.toTypedArray(),
        flow = flow?.toJs(),
    )

internal fun AssistEvent.Similar.toJs(): SimilarPartJs =
    SimilarPartJs(similar.map { it.toJs() }.toTypedArray(), noveltyHint.name)

private fun SimilarInnovationDto.toJs(): SimilarInnovationJs = SimilarInnovationJs(innovation.toJs(), score)

internal fun SuggestionDto.toJs(): SuggestionJs =
    SuggestionJs(title, rationale, nextStep, basedOnInnovationIds.toTypedArray())

internal fun FlowDto.toJs(): FlowJs = FlowJs(actors.toTypedArray(), steps.map { it.toJs() }.toTypedArray())

private fun FlowStepDto.toJs(): FlowStepJs = FlowStepJs(from, to, label)
